export const AUTH = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
}

export const AUCTION ={
  LIST_REQUEST:'LIST_REQUEST',
  LIST_SUCCESS:'LIST_SUCCESS',
  LIST_FAILURE:'LIST_FAILURE'
}

export const REFERENCEDATA = {
  FETCH_ALL: 'LOAD_REFERENCE_DATA',
  LOAD_MATERIALS: 'LOAD_MATERIALS'
}

export const LOT ={
  CHECK_SUCCESS:'LOTCHECK_SUCCESS',
  CHECK_FAILURE:'LOTCHECK_FAILURE'
}
